[package]
name = "ascot-esp32c3"
version = "0.1.0"
edition = "2021"

[dependencies]
ascot-library = { path = "../" }
anyhow = "1"
embedded-svc = { version = "0.28", default-features = false }
esp-idf-svc = "0.49.0"
heapless = "0.8.0"
log = { version = "0.4", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
